src/Podorozhniki/MainBundle/Form/RideType.php
<?php

namespace Podorozhniki\MainBundle\Form;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class RideType extends AbstractType
{
    protected $user;

    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */


    public function __construct(\FOS\UserBundle\Entity\User $user)
    {
        $this->user = $user;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('who',null,array('multiple'=>false,'expanded'=>true,'attr'=>array('data-toggle'=>"buttons","class"=>"btn-group")))
            ->add('departure', null, array('attr' => array('autocomplete' => 'on','onblur'=>'setMarkerFromName("departure","a")')))
            ->add('destination', null, array('attr' => array('autocomplete' => 'on', 'onblur' => 'setMarkerFromName("destination","b")')))
            ->add('distance',null,array('attr'=>array('readonly'=>'readonly')))
            ->add('departuretime', 'datetime', array('input' => 'datetime', 'widget' => 'single_text'))
            ->add('departureanytime')
            ->add('numberofseats')

            ->add('currency',null,array('multiple'=>false,'expanded'=>true,'attr'=>array('data-toggle'=>"buttons","class"=>"btn-group")))
            ->add('oneseatcost')
            ->add('returndate', 'datetime', array('input' => 'datetime', 'widget' => 'single_text'))
            ->add('returnanytime')
            ->add('departurelongitude','hidden')
            ->add('departurelatitude','hidden')
            ->add('destinationlongitude','hidden')
            ->add('destinationlatitude','hidden')
            ->add('route','hidden')
            ->add('user', 'entity', array('class' => 'ApplicationSonataUserBundle:User', 'query_builder' => function (EntityRepository $er) {
                    return $er->createQueryBuilder('u')->where('u.id=:id')->setParameter('id', $this->user->getId());
                }, 'attr' => array('class' => 'invisible'), 'label_attr' => array('class' => 'invisible')))
            ->add('Add', 'submit');

    }

    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'Podorozhniki\MainBundle\Entity\Ride'
        ));
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'podorozhniki_mainbundle_ride';
    }
}

src/Podorozhniki/MainBundle/Controller/UserRidesController.php
<?php

namespace Podorozhniki\MainBundle\Controller;

use FOS\RestBundle\Controller\FOSRestController;
use Podorozhniki\MainBundle\Entity\Ride;
use Podorozhniki\MainBundle\Form\RideType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;

class UserRidesController extends FOSRestController
{

    public function getRidesAction($userId)
    {
        $em = $this->get('doctrine.orm.entity_manager');
        $paginator = $this->get('knp_paginator');

        if( !is_object($this->getUser()) || ( is_object($this->getUser()) &&$this->getUser()->getId()!=$userId)){
            throw new AccessDeniedException("У вас нет доступ к этому ресурсу!");
        }
            $rides = $em->getRepository("PodorozhnikiMainBundle:Ride")->PaginateFindAllByUser($paginator,$this->getRequest(),5,$this->getUser());
            return $this->render("PodorozhnikiMainBundle:UserRides:getRides.html.twig", array("rides" => $rides));
    }

    public function getRideAction($userId, $id)
    {
        $ride = $this->getDoctrine()->getRepository("PodorozhnikiMainBundle:Ride")->find($id);
        return $this->render("PodorozhnikiMainBundle:UserRides:getRide.html.twig", array("ride" => $ride));
    }

    public function postRideAction($userId, Request $request)
    {
        $ride = new Ride();
        $form = $this->createForm(new RideType($this->getUser()), $ride);
        $form->handleRequest($request);
        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($ride);
            $em->flush();

            return $this->redirect($this->generateUrl("get_user_ride",array('userId'=>$ride->getUser()->getId(),'id'=>$ride->getId())));
        }
        return new Response("PodorozhnikiMainBundle:UserRides:postRides.html.twig", array("form" => $form->createView()));

    }

    public function newRideAction($userId)
    {
        if (is_object($this->getUser()) && $userId == $this->getUser()->getId()) {
            $ride = new Ride();
            $form = $this->createForm(new RideType($this->getUser()), $ride, array('action' => $this->generateUrl('post_user_ride', array('userId' => $userId)), 'method' => 'post'));
            return $this->render("PodorozhnikiMainBundle:UserRides:newRide.html.twig", array("form" => $form->createView()));
        } else {
            return $this->redirect($this->generateUrl("podorozhniki_main_homepage"));
        }

    }

}

src/Podorozhniki/MainBundle/Resources/views/UserRides/getRide.html.twig
{% extends "::base.html.twig" %}
{% block body %}
<div class="col-lg-4 col-sm-6">
    <table class="record_properties">
        <tbody>
        <tr>
            <th>{{ ride.who.name|trans }}</th>
            <td>{{ ride.user.firstname }}</td>
        </tr>
        <tr>
            <th>{{ 'Departure'|trans }}</th>
            <td>{{ ride.departure }}</td>
        </tr>
        <tr>
            <th>{{ 'Destination'|trans }}</th>
            <td>{{ ride.destination }}</td>
        </tr>
        <tr>
            <th>{{ 'Departuretime'|trans }}</th>
            <td>{{ ride.departuretime|date('Y-m-d H:i:s') }}</td>
        </tr>
        <tr>
            <th>{{ 'Departureanytime'|trans }}</th>
            <td>{{ ride.departureanytime }}</td>
        </tr>

        <tr>
            <th>{{ 'Oneseatcost'|trans }}</th>
            <td>{{ ride.oneseatcost }}</td>
        </tr>
        <tr>
            <th>{{ 'Returndate'|trans }}</th>
            <td>{{ ride.returndate|date('Y-m-d H:i:s') }}</td>
        </tr>
        <tr>
            <th>{{ 'Returnanytime'|trans }}</th>
            <td>{{ ride.returnanytime }}</td>
        </tr>
        </tbody>
    </table>
</div>
{% endblock %}

src/Podorozhniki/MainBundle/Resources/views/UserRides/getRides.html.twig
{% extends "::base.html.twig" %}

{% block title %}PodorozhnikiMainBundle:Rides:getRides{% endblock %}

{% block body %}
    <h1>{{ 'routes.all'|trans }}</h1>
    <table class="table table-responsive table-hover">
        <thead>
        <tr>
            <th>{{ 'Who'|trans }}</th>
            <th>{{ 'Firstname'|trans }}</th>
            <th>
                <span class="glyphicon {% if app.request.get('direction') == 'asc' %} glyphicon-up-arrow {% elseif app.request.get('direction') == 'desc' %}glyphicon-down-arrow{% endif %}"></span> {{ knp_pagination_sortable(rides,'Departure'|trans,'r.departure') }}
            </th>
            <th>{{ 'Destination'|trans }}</th>
            <th><span class="glyphicon glyphicon-clock"></span></th>
            <th>{{ 'Seatsleft'|trans }}</th>
        </tr>
        </thead>
        <tbody>
        {% for ride in rides %}

            <tr class="cursor"
                onclick="location.href ='{{ path('get_user_ride',{'userId': ride.user.id,'id': ride.id}) }}' ">
                <td>
                    <span class="glyphicon {% if ride.who|trans({},'messages','en')=='Driver' %} glyphicon-car  {% else %} glyphicon-user{% endif %}"></span>
                </td>
                <td>{{ ride.user.firstname|capitalize }}</td>
                <td>{{ ride.departure }}</td>
                <td>{{ ride.destination }}</td>
                <td>{{ ride.departuretime | localizeddate('short','none',app.request.locale) }}
                    {{ 'at'|trans }} {{ ride.departuretime|date('h:m') }}</td>
                <td>{{ ride.numberofseats }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {{ knp_pagination_render(rides) }}
{% endblock %}

src/Podorozhniki/MainBundle/Resources/views/UserRides/newRide.html.twig
{% extends '::base.html.twig' %}

{% block body %}
    {% form_theme form ':Form:fields.html.twig' %}
    <div class="row">
        <div class="col-md-6">
            {{ form(form,{'attr':{'class':'form-horizontal'}}) }}
        </div>

    <div class="col-md-6">
        <div id="map-canvas" class="hidden-xs"></div>
    </div>
    </div>
{% endblock %}